Adds OpenStreetMap contributors attribution
vostpt/rallyapp pull request #2
Opened 2021-05-21 10:14 UTC by SrNetoChan

The basemap provided by mapbox API has an incomplete attribution.

2021-05-21 15:17 UTC, marado requested changes
De acordo com https://www.openstreetmap.org/copyright, "For a browsable electronic map, the credit should appear in the corner of the map." Esta alteração (que também pode ser feita) não resolve o problema dos créditos do mapa. Outras soluções foram propostas em #1 .

2021-05-21 17:56 UTC, SrNetoChan commented
> De acordo com https://www.openstreetmap.org/copyright, "For a browsable electronic map, the credit should appear in the corner of the map." Esta alteração (que também pode ser feita) não resolve o problema dos créditos do mapa. Outras soluções foram propostas em #1 .

@marado não tinha reparado no issue, nem nas possíveis sugestões. Vou investigar. Não é bem a minha praia.

2021-05-22 01:27 UTC, JorgeMiguelGomes approved these changes
Approved. Will be deployed as soon as possible.

2021-05-22 01:27 UTC, merged

2021-05-22 08:57 UTC, SrNetoChan commented
Thanks @JorgeMiguelGomes !